<?php
require_once __DIR__ . '/../config/app.php';
requireLogin();
if (!isStaff()) { setFlash('error', 'Staff access only.'); redirect('/holy-trinity/index.php'); }

$db = Database::getInstance();
$userId = $_SESSION['user_id'];
$userRole = $_SESSION['user_role'];

$staffMeta = [
    'guard' => ['icon' => 'fa-shield-halved', 'color' => '#1a365d', 'gradient' => 'linear-gradient(135deg,#1a365d,#2c5282)'],
    'house_helper' => ['icon' => 'fa-house-chimney', 'color' => '#7b2cbf', 'gradient' => 'linear-gradient(135deg,#7b2cbf,#9d4edd)'],
    'general_worker' => ['icon' => 'fa-hard-hat', 'color' => '#e85d04', 'gradient' => 'linear-gradient(135deg,#e85d04,#f48c06)'],
];
$meta = $staffMeta[$userRole] ?? $staffMeta['general_worker'];

$payslips = $db->fetchAll("SELECT * FROM payslips WHERE staff_user_id = ? ORDER BY pay_date DESC", [$userId]);
$totalEarned = array_sum(array_column($payslips, 'net_pay'));
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php include_once __DIR__ . "/../includes/pwa-head.php"; ?>
    <title>My Payslips | <?= APP_NAME ?></title>
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="/holy-trinity/assets/css/style.css">
</head>
<body>
    <div class="dashboard-layout">
        <aside class="sidebar" style="background:<?= $meta['gradient'] ?>;">
            <div class="sidebar-brand" style="background:rgba(0,0,0,0.2);"><i class="fas <?= $meta['icon'] ?>"></i><span>Staff Portal</span></div>
            <nav class="sidebar-menu">
                <div class="sidebar-section">My Dashboard</div>
                <a href="/holy-trinity/staff/dashboard.php"><i class="fas fa-tachometer-alt"></i> Dashboard</a>
                <a href="/holy-trinity/staff/attendance.php"><i class="fas fa-clock"></i> My Attendance</a>
                <a href="/holy-trinity/staff/payslips.php" class="active"><i class="fas fa-file-invoice-dollar"></i> My Payslips</a>
                <a href="/holy-trinity/staff/leave.php"><i class="fas fa-calendar-minus"></i> Leave Requests</a>
                <div class="sidebar-section">Account</div>
                <a href="/holy-trinity/portal/profile.php"><i class="fas fa-user-edit"></i> My Profile</a>
                <a href="/holy-trinity/auth/logout.php"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </nav>
        </aside>
        <div class="dashboard-main">
            <h2 style="font-family:'Cinzel',serif; color:<?= $meta['color'] ?>; margin-bottom:1.5rem;"><i class="fas fa-file-invoice-dollar"></i> My Payslips</h2>

            <div class="card">
                <div class="card-body" style="padding:0;">
                    <?php if (empty($payslips)): ?>
                        <p class="text-muted text-center" style="padding:2rem;">No payslips available yet. Payslips will appear here once generated by the parish office.</p>
                    <?php else: ?>
                    <div class="table-responsive">
                        <table class="table">
                            <thead><tr><th>Pay Period</th><th>Pay Date</th><th>Basic</th><th>Deductions</th><th>Net Pay</th><th>Status</th><th>Action</th></tr></thead>
                            <tbody>
                            <?php foreach ($payslips as $ps): ?>
                            <tr>
                                <td><strong><?= sanitize($ps['pay_period']) ?></strong></td>
                                <td><?= formatDate($ps['pay_date']) ?></td>
                                <td>ZMW <?= number_format($ps['basic_salary'], 2) ?></td>
                                <td style="color:#ef4444;">ZMW <?= number_format($ps['deductions'] + $ps['tax'] + $ps['napsa'] + $ps['nhima'], 2) ?></td>
                                <td><strong style="color:#22c55e;">ZMW <?= number_format($ps['net_pay'], 2) ?></strong></td>
                                <td><span class="badge badge-<?= $ps['status'] === 'paid' ? 'success' : ($ps['status'] === 'approved' ? 'info' : 'warning') ?>"><?= ucfirst($ps['status']) ?></span></td>
                                <td>
                                    <a href="/holy-trinity/staff/payslip-download.php?id=<?= $ps['id'] ?>" class="btn btn-sm btn-outline" style="font-size:0.8rem;"><i class="fas fa-download"></i> View</a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr style="background:#f8fafc;"><td colspan="4" style="text-align:right;"><strong>Total Earned:</strong></td><td colspan="3"><strong style="color:#22c55e;">ZMW <?= number_format($totalEarned, 2) ?></strong></td></tr>
                            </tfoot>
                        </table>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <script src="/holy-trinity/assets/js/main.js"></script>
    <?php include_once __DIR__ . "/../includes/pwa-sw.php"; ?>
</body>
</html>
